# Generated by Django 2.0.6 on 2018-12-31 16:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='intro',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
