# Generated by Django 2.0.1 on 2018-07-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
