# Generated by Django 2.0.6 on 2018-09-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postapproval',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='postapproval',
            name='title',
        ),
        migrations.DeleteModel(
            name='PostApproval',
        ),
    ]
