# Generated by Django 2.0.6 on 2018-10-11 15:10

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180928_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
