# Generated by Django 2.0.6 on 2018-12-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181202_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(default='mashwani'),
            preserve_default=False,
        ),
    ]
