# Generated by Django 2.0.6 on 2018-10-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181016_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
    ]
