# Generated by Django 2.0.6 on 2018-12-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181206_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skillset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='SkillSet',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
