# Generated by Django 2.0.6 on 2018-10-18 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181017_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(),
        ),
    ]
