# Generated by Django 2.0.6 on 2018-11-03 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20181026_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='request_from',
            field=models.CharField(choices=[('api', 'api'), ('template', 'template')], default='api', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 3, 19, 5, 23, 552864)),
            preserve_default=False,
        ),
    ]
