# Generated by Django 2.0.6 on 2018-11-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181103_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='request_from',
            field=models.CharField(choices=[('api', 'api'), ('template', 'template')], default='api', max_length=10),
        ),
    ]
