# Generated by Django 2.0.6 on 2018-11-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
